@startuml
actor Customer
actor "ATM Technician" as tech
actor Bank



left to right direction
rectangle "Bank ATM"<< subsistem >>{
    usecase "Check Balances" as cb
    usecase "Deposit Funds" as df
    usecase "Withdraw Cash" as wc
    usecase "Transfer Funds" as tf
    usecase "Maintenance" as mtc
    usecase "Repair" as rep
}

Customer--cb
Customer--df
Customer--wc
Customer--tf
tech--mtc
tech--rep

cb--Bank
df--Bank
wc--Bank
tf--Bank
mtc--Bank
rep--Bank
@enduml