services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html:cached
    working_dir: /var/www/html
    user: www-data
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      PHP_IDE_CONFIG: "serverName=invci"
      database.default.hostname: db
      database.default.database: invci
      database.default.username: invci
      database.default.password: invci
      database.default.DBDriver: MySQLi
      database.default.port: 3306
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sleep infinity
    networks:
      - invci-networks

volumes:
  db-data:

networks:
  invci-networks:
    driver: bridge
